//! Compiled protobuf types for gRPC services.
//!
//! Generated by prost-build in `build.rs` from `construct-protos`.
//! Module hierarchy mirrors proto packages:
//!   `shared.proto.core.v1`      → `proto::core::v1`
//!   `shared.proto.messaging.v1` → `proto::messaging::v1`
//!   `shared.proto.services.v1`  → `proto::services::v1`
//!   `shared.proto.signaling.v1` → `proto::signaling::v1`

#![allow(dead_code)]

/// Core types: Envelope, Identity, Crypto, Pagination.
pub mod core {
    pub mod v1 {
        #![allow(clippy::large_enum_variant, clippy::doc_lazy_continuation)]
        include!(concat!(env!("OUT_DIR"), "/shared.proto.core.v1.rs"));
    }
}

/// Messaging wire types: MessageContent, session control.
pub mod messaging {
    pub mod v1 {
        #![allow(clippy::large_enum_variant, clippy::doc_lazy_continuation)]
        include!(concat!(env!("OUT_DIR"), "/shared.proto.messaging.v1.rs"));
    }
}

/// Service request/response types: Auth, Key, Messaging, User, Notification.
pub mod services {
    pub mod v1 {
        #![allow(clippy::large_enum_variant, clippy::doc_lazy_continuation)]
        include!(concat!(env!("OUT_DIR"), "/shared.proto.services.v1.rs"));
    }
}

/// Signaling types: DeliveryReceipt, PresenceUpdate, WebRTC.
pub mod signaling {
    pub mod v1 {
        #![allow(clippy::large_enum_variant, clippy::doc_lazy_continuation)]
        include!(concat!(env!("OUT_DIR"), "/shared.proto.signaling.v1.rs"));
    }
}
